version: '3.8'

services:
  app-cpu:
    image: jeanmag/facial-recognition-arida:cpu
    ports:
      - "80:8000"
    restart: unless-stopped
    volumes:
      - /caminho/no/host/para/referencias:/app/db/rostos_dataset
      - /caminho/no/host/para/novas_imagens:/app/db/novas_imagens
      - /caminho/no/host/para/db_files:/app/db/index
    environment:
      - PASTA_REFERENCIAS=/app/db/rostos_dataset
      - PASTA_NOVAS_IMAGENS=/app/db/novas_imagens

  app-gpu:
    image: jeanmag/facial-recognition-arida:gpu
    ports:
      - "80:8000"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    runtime: nvidia
    restart: unless-stopped
    volumes:
      - /caminho/no/host/para/referencias:/app/db/rostos_dataset
      - /caminho/no/host/para/novas_imagens:/app/db/novas_imagens
      - /caminho/no/host/para/db_files:/app/db/index
    environment:
      - PASTA_REFERENCIAS=/app/db/rostos_dataset
      - PASTA_NOVAS_IMAGENS=/app/db/novas_imagens
